### PR TITLE
Full Rework of the Library

### PR DESCRIPTION
**Pull request by EldoranDev**
We need to rework the base structure of the wrapper to handle the response headers of the League API.

**Callback Deprecation**
Current Stable version of NodeJS is 4.6 and brings a version of v8 that fully supports Promises to avoid callback hell i'll try to promisifie everything.

**Caching**
We currently have a rate limiter, but we could cache certain requests so we give a result even if rate is blocked (Summoner Match history often does not change faster as once every 20-30 mins etc)

**Response Headers**
The League API is sending rate information since a few versions so we can adjust our rate limiting behavior.

I'll try to coordinate this changes as best as possible with @claudiowilson to not change his product to much.

### CODE REVIEW

**Comment by Colorfulstan** [comment]
I personally think it would be a good idea to start with the more general changes that are compatible with both, promises and callbacks instead of starting with promisifying everything.

Provides more general value and promisifying isn't really a big deal when using libraries like bluebird.
Things like missing possibilites for options to the api and error-handling capabilities for example yield much more value in general

**Comment by EldoranDev** [comment]
@Colorfulstan your propably right. i'll focus on the config part and error handling.

**Comment by EldoranDev** [comment]
The current sample implementation would be the way i would reimplement the hole system. If someone has some suggestions or criticism I am open to changes and pull requests based on the "rework" branch.

**Comment by Colorfulstan** [comment]
From a quick glance it seems fine. You're keeping the public API intact I assume?

**Comment by claudiowilson** [comment]
I think it's wise to keep backwards compatibility if we want to phase things out, it makes sense to maybe log in the console that something is deprecated instead of just removing it completely to give people time to migrate

**Comment by EldoranDev** [comment]
I'll integrate the layer for deprecation warnings and backwards compatibility in one of my next commits, just wanted to get the the new structure and error-handling working.

**Comment by 0x300** [comment]
@EldoranDev Are you planning on adding the API documentation back into the README.md file or will it be elsewhere? That reference was great for me because I didn't need to dig deep to find the information I needed to use this. Guessing you're probably still working on stuff for this PR but I wanted to say something just in case :)

**Comment by EldoranDev** [comment]
Of course, I'll be working on this PR from the 16th again, and i'll write a new readme and a migration guide (even we have the Compatibility layer in between).

**Comment by Colorfulstan** [comment]
Moved to https://github.com/Colorfulstan/LeagueJS published separately on npm for the time being.
We might consider combining the repos sometime in the future for better maintainability (can't open issues on a fork etc.)

**Pull request closed without merging**
